### PR TITLE
Build systems: fixes

### LINKED ISSUE #86: seems there was some things forgotten on different build configs
If using the following, the files mentioned are forgotten/missed during installation
- Makefile: The systemd service file
- Meson: hyprland-share-picker

Not sure which you prefer but I will wait for a small patch ❤️

### PR DESCRIPTION
**Pull request by fufexan**
Fixes #86.

- Makefile: properly handle dbus & systemd services
- Meson: build hyprland-share-picker with meson
- Nix: combine xdph and the picker into one package.

### CODE REVIEW

**Comment by vaxerski** [comment]
are you linking qt6?

**Comment by fufexan** [comment]
Should be linked just by being in the `dependencies` key.

**Comment by vaxerski** [comment]
idk meson so good luck

**Comment by vaxerski** [comment]
oops my bad

**Pull request merged**
