### PR TITLE
core: move to sdbus-cpp2

### PR DESCRIPTION
**Pull request by vaxerski**
Works, needs testing. Screencopy seems to be doin good

@fufexan ci

### CODE REVIEW

**Comment by VirtCode** [comment]
Working fine for me too so far, tested screencopy with OBS and Vesktop. Is there something other than screencopy that would need testing?

**Comment by vaxerski** [comment]
color picking and global shortcuts, ideally

**Comment by Agent00Ming** [comment]
Any clients known to use the GlobalShortcuts portal? Screenshots and color picking seem to work fine.

**Comment by VirtCode** [comment]
Can confirm that the Screenshot portal with PickColor is working fine.

I also tested GlobalShortcuts (managed to find one of the rare programs that actually have support for it) and they also work as expected. So I think this is good to go.

For future reference, here's how I tested the GlobalShortcuts:
I used [gpu-screen-recorder-gtk-git](https://aur.archlinux.org/packages/gpu-screen-recorder-gtk-git) but had to patch out an exception which was related to a fixed issue. 

1. install [gpu-screen-recorder-git](https://aur.archlinux.org/packages/gpu-screen-recorder-git) from the AUR
2. clone https://repo.dec05eba.com/gpu-screen-recorder-gtk ([webpage](https://git.dec05eba.com/gpu-screen-recorder-gtk/about/))
3. patch out the hyprland exception with the following patch
```diff
diff --git a/src/main.cpp b/src/main.cpp
index b8c0e71..0d9253e 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -4006,7 +4006,7 @@ static void activate(GtkApplication *app, gpointer) {
         // instead of having a "register hotkeys" button. This needed because Hyprland doesn't remember registered hotkeys after
         // the desktop portal is restarted (when the computer is restarted for example).

-        if(wayland_compositor == WaylandCompositor::HYPRLAND) {
+        if(wayland_compositor == WaylandCompositor::HYPRLAND && false) {
             const char *hotkeys_not_supported_text = "Global hotkeys have been disabled on your system because of a Hyprland bug.\nUse X11 or KDE Plasma on Wayland if you want to use hotkeys.";
             gtk_label_set_text(GTK_LABEL(recording_hotkeys_not_supported_label), hotkeys_not_supported_text);
             gtk_label_set_text(GTK_LABEL(replay_hotkeys_not_supported_label), hotkeys_not_supported_text);
```
4. build and run the program
5. select "Record" and click "Change hotkeys"
6. (see shortcuts with `hyprctl globalshortcuts`
7. bind to one of the shortcuts `hyprctl keyword bind SUPER, Z, global, :gpu_screen_recorder_start_stop_recording`
8. test

**Comment by vaxerski** [comment]
cool, thanks!

**Pull request merged**
