### PR TITLE
[WIP] Full rewrite, v1.0 release.

### PR DESCRIPTION
**Pull request by vaxerski**
TODO:
 - [x] GlobalShortcuts portal
 - [ ] Config?
 - [ ] @fufexan meson and nix
 - [ ] @fufexan CI
 - [x] Better restore tokens

Comments welcome.

Build instructions in the README of the branch.

### CODE REVIEW

**Comment by Teddy-Kun** [comment]
Not 1 application I use (Firefox, OBS, or a modified Discord) even detect pipewire screensharing being available. The logs of the portal seem weirdly fine though. Also the portal does not start automatically when Hyprland starts so that could be one of the reasons.
https://pastebin.com/vqJrSDhs

**Comment by vaxerski** [comment]
image

Try this, adjust paths as needed.

**Comment by DashieTM** [comment]
I tested screenshare with discord-screenaudio and firefox, seems to work just like before, will do more testing with a longer period of time once I have someone to watch it on the other end.

Small note, you should prob write the need for a systemd or whatever init system file in the readme.

**Comment by vaxerski** [comment]
it ideally should work exactly as before, with the only difference maybe being less bugs :P

**Comment by vaxerski** [comment]
this is about the state of something I'd be happy with merging.

If you encounter any bugs, please let me know so that they can be fixed prior to merging.

@fufexan for meson and nix

**Comment by vaxerski** [comment]
wooo

**Pull request merged**
