### PR TITLE
Unbreak build on FreeBSD

### PR DESCRIPTION
**Pull request by jbeich**

### CODE REVIEW

**Comment by jbeich** [comment]
Found another regression (only affects libc++):
```
/usr/bin/ld: src/xdg-desktop-portal-hyprland.p/core_PortalManager.cpp.o: undefined reference to symbol 'pthread_create@@FBSD_1.0'
/usr/bin/ld: /lib/libthr.so.3: error adding symbols: DSO missing from command line
```

**Comment by jbeich** [comment]
Done. Tested both CMake and Meson.

**Comment by jbeich** [comment]
Sorry for multiple force-pushes. I wanted to document error messages better. GCC is good nowadays but its linker (GNU bfd) is still obtuse.

**Review by vaxerski — APPROVED** [review]
thanks!

**Pull request merged**
